export const RATES_LOADED = 'RATES_LOADED';
export const RATES_DETAILS_LOADED = 'RATES_DETAILS_LOADED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_COMPLETE = 'REGISTER_USER_COMPLETE';
