export const RATES_LOADED = 'RATES_LOADED';
export const RATES_DETAILS_LOADED = 'RATES_DETAILS_LOADED';

export const REGISTER_USER_COMPLETE = 'REGISTER_USER_COMPLETE';
export const REGISTER_USER_ERROR = 'REGISTER_USER_COMPLETE';

export const LOGIN_USER_COMPLETE = 'LOGIN_USER_COMPLETE';
export const LOGIN_USER_ERROR = 'LOGIN_USER_COMPLETE';

export const LOGOUT_USER_COMPLETE = 'LOGOUT_USER_COMPLETE';

export const NOTIFICATIONS_LOADED = 'NOTIFICATIONS_LOADED';